### ISSUE TITLE
Don't Work in ECS6 

### ISSUE THREAD

**Issue by michael158** [darrynten/vue-adsense#3]
The following error is show:
"Cannot assign to read only property 'exports' of object '#<Object>'"

**Comment by tsauvajon** [comment]
I have the same error :

Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'


​

**Comment by maartenpaauw** [comment]
Having the same error. When will the PR be accepted?

**Comment by tsauvajon** [comment]
While waiting you can either fork it and replicate the change (CommonJS export to Es6 export) or fork this https://github.com/tsauvajon/vue-adsense (I've just changed the one line to make it work), or michael158's one  : https://github.com/michael158/vue-adsense. 
It doesn't work because you can't mix CommonJS exports with Es6 imports.

**Comment by tsauvajon** [comment]
Or michael158 one of course https://github.com/michael158/vue-adsense

**Comment by darrynten** [comment]
This has been resolved, thanks for all the assistance and patience, it's most appreciated
